services:
    mysqldb:
        container_name: mysql-tfi-db
        image: mysql:9.0
        restart: always
        environment:
            MYSQL_USER: ${DOCKER_SQL_USER}
            MYSQL_PASSWORD: ${DOCKER_SQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DOCKER_SQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DOCKER_SQL_DATABASE}
        ports:
            - '3306:3306'
        volumes:
            - mysql-tfi-data:/var/lib/mysql
    gtfs-db-testing:
        container_name: gtfs-db-testing
        image: matthewoleary/gtfs-db-testing:20260316
        restart: always
        ports:
        - '3307:3306'
        environment:
            MYSQL_USER: ${TEST_DOCKER_SQL_USER}
            MYSQL_PASSWORD: ${TEST_DOCKER_SQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${TEST_DOCKER_SQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${TEST_DOCKER_SQL_DATABASE}

volumes:
    mysql-tfi-data: